
# Adjust here the quantum (aka buffer)

# The commented out below values are the standard defaults
# as in /usr/share/pipewire/pipewire.conf
#default.clock.quantum       = 1024
#default.clock.min-quantum   = 32
#default.clock.max-quantum   = 2048
#default.clock.quantum-limit = 8192
#default.clock.quantum-floor = 4

context.properties = {
    default.clock.quantum       = 1024
    default.clock.min-quantum   = 1024
    default.clock.max-quantum   = 4096
}

