# YAML

# List of playback Apps to be queried so that speed up the response
# (i) Leave blank or comment out below to query all available
#     The first one has precedence if more than one are found
#     in 'play' state.

preferred apps:

    - Spotify
    - Music
    # - QuickTime Player
    # - VLC
    # - IINA

